version: "3.7"
services:
  app:
    build:
      args:
        user: php
        uid: 801
      context: ./
      dockerfile: Dockerfile
    image: php-app
    container_name: php-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - php-app

  db:
    image: mysql:8.0
    container_name: php-app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - php-app

  nginx:
    image: nginx:alpine
    container_name: php-app-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - php-app

networks:
  php-app:
    driver: bridge